services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    container_name: sheriff-postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=sheriff-db
    ports:
      - 5432:5432
    volumes:
      - ~/.docker/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "docker", "-d", "sheriff-db"]
      interval: 10s
      timeout: 5s
      retries: 5
